version: '2.0'

services:
  jupyter:
    build: 
      context: .
      args:
        J_USER: ${J_USER}
        J_PASS: ${J_PASS}
    volumes:
      - /home/gonzalo/data:/data
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./notebooks:/home/${J_USER}/notebooks
 #     - .:/code
 #     - ./remoteshelloverfs/shared:/shared
 #     - ./import_images:/tmp/ncem_images
 #     - ./preview_images:/tmp/preview_images
    ports:
      - "7979:7979"
 #   depends_on:
 #     - db
    environment:
      - J_USER
 #     - FILE_SHELL_COMMANDS=/shared/command.txt
 #     - FILE_SHELL_OUTPUT=/shared/output.txt
 #     - FILE_SHELL_DIR=/code/remoteshelloverfs
 #     - FILE_SHELL_ENABLE=1gonzalo-pro:dtndocker gonzalo$

  grid-ftp1:
    build: 
      context: ./gftp
      args:
         CONF_FILE: gridftp.conf.112
    volumes:
      - /home/gonzalo/data:/data
    ports:
      - "192.168.112.2:9002:9002"
      - "192.168.112.2:50000-50300:50000-50300"
    environment:
      - PUBLIC_IP=192.168.112.2
  grid-ftp2:
    build: 
      context: ./gftp
      args:
         CONF_FILE: gridftp.conf.200
    volumes:
      - /home/gonzalo/data:/data
    ports:
      - "192.168.200.2:9002:9002"
      - "192.168.200.2:50000-50300:50000-50300"
    environment:
      - PUBLIC_IP=192.168.200.2
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000
