version: '2.0'

services:
  jupyter:
    build: 
      context: .
      args:
        J_USER: ${J_USER}
        J_PASS: ${J_PASS}
    volumes:
      - /home/gonzalo/data:/data
      - /etc/letsencrypt/:/etc/letsencrypt/
 #     - .:/code
 #     - ./remoteshelloverfs/shared:/shared
 #     - ./import_images:/tmp/ncem_images
 #     - ./preview_images:/tmp/preview_images
    ports:
      - "8000:8000"
 #   depends_on:
 #     - db
    environment:
      - J_USER
 #     - FILE_SHELL_COMMANDS=/shared/command.txt
 #     - FILE_SHELL_OUTPUT=/shared/output.txt
 #     - FILE_SHELL_DIR=/code/remoteshelloverfs
 #     - FILE_SHELL_ENABLE=1gonzalo-pro:dtndocker gonzalo$

  grid-ftp1:
    build: ./gftp
    volumes:
      - /home/gonzalo/data:/data
    ports:
      - "192.168.112.2:2811:2811"
      - "192.168.112.2:9000-8254:9000-8254"
  grid-ftp2:
    build: ./gftp
    volumes:
      - /home/gonzalo/data:/data
    ports:
      - "192.168.200.2:2811:2811"
      - "192.168.200.2:9000-8254:9000-8254"
