version: '3.2'

services:
  jupyter:
    build: .
    volumes:
      - ./files_storage:/tmp/files_storage
 #     - .:/code
 #     - ./remoteshelloverfs/shared:/shared
 #     - ./import_images:/tmp/ncem_images
 #     - ./preview_images:/tmp/preview_images
    ports:
      - "8000:8000"
 #   depends_on:
 #     - db
 #   environment:   
 #     - FILE_SHELL_COMMANDS=/shared/command.txt
 #     - FILE_SHELL_OUTPUT=/shared/output.txt
 #     - FILE_SHELL_DIR=/code/remoteshelloverfs
 #     - FILE_SHELL_ENABLE=1gonzalo-pro:dtndocker gonzalo$

  grid-ftp1: 
    build: ./gridftp/docker/dtn-anonymous-gridftp
    volumes:
      - ./files_storage:/data
    ports: 
      - "192.168.56.10:2811:2811"
      - "192.168.56.10:50000-51000:50000-51000"
      - "192.168.56.10:4823:4823"
      - "192.168.56.10:5001-5900:5001-5900"
      - "192.168.56.10:6001-6200:6001-6200"
      - "192.168.56.10:861:861"
      - "192.168.56.10:8760-9960:8760-9960"

  grid-ftp2: 
    build: ./gridftp/docker/dtn-anonymous-gridftp
    volumes: 
      - ./files_storage:/data
    ports: 
      - "192.168.56.11:2811:2811"
      - "192.168.56.11:50000-51000:50000-51000"
      - "192.168.56.11:4823:4823"
      - "192.168.56.11:5001-5900:5001-5900"
      - "192.168.56.11:6001-6200:6001-6200"
      - "192.168.56.11:861:861"
      - "192.168.56.11:8760-9960:8760-9960"
